### PR TITLE
Redesign assignment dialog - remove 'all' button

### PR DESCRIPTION
**Pull request by DakshSaini**
This pull request addresses bullet point 1 in issue #65

### CODE REVIEW

**Comment by DakshSaini** [comment]
@amdw, can I get a review? Thanks!

**Review by amdw — CHANGES_REQUESTED** [review]
Many thanks for sending this pull request!

In terms of *functionality*, I think it's actually the "remaining" button we want to keep.

This will assign all the unassigned work on the objective to the selected person, up to the maximum they have available. If the objective is completely unassigned, then it will have the same effect as the "all" button used to have.

I'm open to the possibility of renaming the button, but I think "remaining" is good enough for now - what do you think?

If you agree, then let's just remove the "all" button instead of the "remaining" button?

Thanks, again, for contributing to PeopleMath!

**Comment by DakshSaini** [comment]
That makes sense! I Fixed it, Thank you @amdw

**Comment by amdw** [comment]
Thank you very much @DakshSaini!

**Pull request merged**
